version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "run tests and shellcheck"
          command: make

workflows:
  version: 2
  basic:
    jobs:
      - test

